name: example

on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: "actions/checkout@v1"
        
      - name: My first step
        run: echo This is the first step of my first job.
